name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      # Ensure .well-known directory is properly handled
      - name: Setup files for proper TOML display
        run: |
          # Make sure stellar.toml is in both locations
          mkdir -p .well-known
          cp stellar.toml .well-known/stellar.toml

          # Create .nojekyll file to bypass Jekyll processing
          touch .nojekyll

          # Create web.config for IIS servers
          cat > web.config << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <configuration>
            <system.webServer>
              <staticContent>
                <mimeMap fileExtension=".toml" mimeType="text/plain" />
              </staticContent>
              <httpProtocol>
                <customHeaders>
                  <add name="Access-Control-Allow-Origin" value="*" />
                </customHeaders>
              </httpProtocol>
            </system.webServer>
          </configuration>
          EOL

          # Create .htaccess for Apache servers
          cat > .htaccess << EOL
          <FilesMatch "\.(toml)$">
            ForceType text/plain
            Header set Access-Control-Allow-Origin "*"
            Header set X-Content-Type-Options "nosniff"
          </FilesMatch>
          EOL

      # Build and upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
